<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="MAIN" Id="{dcf86679-b5e8-4481-bba3-406704c5d86b}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	nCounter : INT;
	nValue	: LREAL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[nCounter := nCounter + 1;]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>